### ISSUE TITLE
Create Wallet feature without layout.

### ISSUE THREAD

**Issue by vanltt** [prdlab/wrappy-iOS#2]
Wallet has these features below:
1. Auto create new account if it's a first time install app on device (with default password)
2. Read and show wallet (ETH, PRO) information from Proteusion private network.
3. Read and show all activities of wallet, and its transaction's information from Proteusion private network.
4. Receive ETH : show address via QRCode for scanning.
5. Send ETH : scan address via QRCode scanner and send ETH to this address.

**Comment by AnhNDT** [comment]
show wallet (ETH, PRO) value, and total in USD

**Comment by vanltt** [comment]
show wallet (ETH, PRO) value, and total in USD => **_DONE_**

**Comment by vanltt** [comment]
This issue was moved to prdlab/wrappy-ios#2
